name: warranty_app
description: AES Warranty Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.0

  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.5
  mobile_scanner: ^7.2.0
  printing: ^5.14.1
  pdf: ^3.11.1
  path_provider: ^2.1.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  barcode: ^2.2.7
  flutter_local_notifications: ^18.0.1
  email_otp: ^2.1.0
  url_launcher: ^6.3.1
  share_plus: ^13.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  package_rename: ^1.10.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/aes_logo.svg
    - assets/logo.png

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"