// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArDgIF4nZ0CZdWILE1aEdmdV0muZFMguE',
    appId: '1:376803339079:web:2a9cac5009c6a05712ba62',
    messagingSenderId: '376803339079',
    projectId: 'aes-warranty',
    authDomain: 'aes-warranty.firebaseapp.com',
    storageBucket: 'aes-warranty.firebasestorage.app',
    measurementId: 'G-J10LF40H74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzocMvfBz5f2ahToVq2l0jOvZuTx1fbhA',
    appId: '1:376803339079:android:226c3137e9d0071c12ba62',
    messagingSenderId: '376803339079',
    projectId: 'aes-warranty',
    storageBucket: 'aes-warranty.firebasestorage.app',
  );
}
